- name: variables from PLAY level
  host: localhost
  vars:               #PLAY Level Variables
   Course: "DevOps"
   Trainer: "Siva"
   Duration: "110HRS"
  tasks:
  - name: check variables
    vars:              #TASK Level Variables
     Course: "DevOps with AWS"
    ansible.builtin.debug:
     msg : "Hi, I am Learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
