- name: variables from PLAY level
  host: localhost
  vars_files:        #Variables calling from file.      
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
     msg : "Hi, I am Learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
