- name: checking data types
  hosts: localhost
  vars:
   NAME: SivaKumar #Key Value Pair
   skills: # Skill is a list type
   - DevOps
   - Shell
   - Ansible
   - Linux
  Experience: # Experience Map type it contains key value pairs
   DevOps: 7
   AWS: 6
   Docker: 4
  Trainer: true # boolean
  tasks:
   -name: print key value pair
    ansible.builtin.debug:
     msg: "name : {{NAME}}"
  
  tasks:
   -name: print list
    ansible.builtin.debug:
     msg: "skills : {{skills}}"

  tasks:
   -name: print map
    ansible.builtin.debug:
     msg: "Experience : {{Experience}}"

  tasks:
   -name: print boolean
    ansible.builtin.debug:
     msg: "is trainer : {{Trainer}}"
  